### ISSUE TITLE
[dss-bridge] censorship resistance

### ISSUE THREAD

**Issue by maciejka** [makerdao/xdomain#60]
Should the design incorporate censorship resistance mechanisms? I mean, as far as I understand basic l1->l2 message passing is not censorship resistant. In order to send noncensorable message DomainHost would need to use ctc api(in optimistic case) instead of l1->l2 message api.

**Comment by hexonaut** [comment]
For Optimistic rollups these are one in the same. As you can see here standard message passing queues onto the CTC: https://github.com/makerdao/xdomain/blob/add-optimism/packages/dss-bridge/src/tests/domains/optimism/OptimismIntegration.t.sol#L320

Is this different for starknet?

**Comment by maciejka** [comment]
Ok, now it is clear that for Optimism it is not a problem.
In case of Starknet forced transactions are yet not implemented.
